apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: teerapatchr04/serverinventory-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-env
