import type { ServerInventory } from "./types";


export const baseServers: ServerInventory[] = [
  {
    id: 1,
    server_name: "art-aads01",
    ip_address: "10.9.5.213",
    application_name: "aads01",
    location: "ART",
    system_environment: "PRD",
    status: "Operation",
    power_state: "On",
    critical_app: "Yes",
    pttep_server_owner: "OCIO",
  },
  {
    id: 2,
    server_name: "bkk-web01",
    ip_address: "10.10.1.45",
    application_name: "web01",
    location: "BKK",
    system_environment: "PRD",
    status: "Operation",
    power_state: "On",
    critical_app: "Yes",
    pttep_server_owner: "BRM",
  },
  {
    id: 3,
    server_name: "dev-app01",
    ip_address: "10.20.3.88",
    application_name: "app01",
    location: "BKK",
    system_environment: "DEV",
    status: "Operation",
    power_state: "On",
    critical_app: "No",
    pttep_server_owner: "OCIO",
  },
  {
    id: 4,
    server_name: "old-legacy01",
    ip_address: "10.5.1.22",
    application_name: "legacy01",
    location: "ART",
    system_environment: "PRD",
    status: "Decommissioning",
    power_state: "Off",
    critical_app: "No",
    pttep_server_owner: "BRM",
  },
  {
    id: 5,
    server_name: "poc-analytics01",
    ip_address: "10.40.2.33",
    application_name: "analytics01",
    location: "BKK",
    system_environment: "POC",
    status: "Operation",
    power_state: "On",
    critical_app: "No",
    pttep_server_owner: "BRM",
  },
  {
    id: 6,
    server_name: "prd-mail01",
    ip_address: "10.9.8.55",
    application_name: "mail01",
    location: "BKK",
    system_environment: "PRD",
    status: "Operation",
    power_state: "On",
    critical_app: "Yes",
    pttep_server_owner: "OCIO",
  },
  {
    id: 7,
    server_name: "qas-erp01",
    ip_address: "10.30.5.77",
    application_name: "erp01",
    location: "ART",
    system_environment: "QAS",
    status: "Operation",
    power_state: "On",
    critical_app: "No",
    pttep_server_owner: "Lead",
  },
  {
    id: 8,
    server_name: "uat-crm01",
    ip_address: "10.31.2.19",
    application_name: "crm01",
    location: "BKK",
    system_environment: "UAT",
    status: "Operation",
    power_state: "On",
    critical_app: "Yes",
    pttep_server_owner: "BRM",
  },
  {
    id: 9,
    server_name: "prd-fin01",
    ip_address: "10.11.9.201",
    application_name: "fin01",
    location: "BKK",
    system_environment: "PRD",
    status: "Operation",
    power_state: "On",
    critical_app: "Yes",
    pttep_server_owner: "OCIO",
  },
  {
    id: 10,
    server_name: "test-batch01",
    ip_address: "10.22.6.10",
    application_name: "batch01",
    location: "ART",
    system_environment: "Test",
    status: "Maintenance",
    power_state: "Off",
    critical_app: "No",
    pttep_server_owner: "BRM",
  },
];

export const mockServers = Array.from({ length: 2000 }, (_, i) => ({
  ...baseServers[i % baseServers.length],
  id: i + 1,
  server_name: `srv-${i + 1}`,
}));
